name: CI
env:
  FORCE_COLOR: 2
  NODE: 14
on:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2026-03-04T15%3A01%3A56.121000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
  regression:
    name: Test regressions
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2026-03-04T15%3A01%3A56.121000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}
          cache: yarn
      - run: yarn install
      - run: yarn test-regression
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 14
          - 12
          - 10
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2026-03-04T15%3A01%3A56.121000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn test-browser
